test-xsd:
  image: alpine:latest
  stage: test
  cache:
    key: apk-cache
    paths:
      - apk-cache/
  before_script:
    - mkdir -p apk-cache
    - ln -s apk-cache /etc/apk/cache
  script:
    - apk update
    - apk add libxml2-utils
    - xmllint --noout dcc.xsd

test-examples:
  image: openjdk:11.0.5
  stage: test
  cache:
    paths:
      - xjparse-app-3.0.0.jar
  script:
    - chmod +x scripts/validateExamples.sh
    - ./scripts/validateExamples.sh
