default:
  image: alpine:latest
  # setup caching for apk (alpine package manager)
  cache:
    key: apk-cache
    paths:
      - apk-cache/
  before_script:
    # create folder for apk cache
    - mkdir -p apk-cache
    # link created folder to /etc/apk/cache
    - ln -s apk-cache /etc/apk/cache
    # update apk index of available packages
    - apk update

# === Job: test-xsd ===
# Description: this job checks the schema for errors.
test-xsd:
  stage: test
  script:
    # install libxml2-utils
    - apk add libxml2-utils
    # check dcc.xsd for errors
    - xmllint --noout dcc.xsd

# === Job: test-examples ===
# Description: this job checks the examples using xerces-c.
# test-examples:
#   stage: test
#   script:
#     - apk add xerces-c-samples
#     - cd examples
#     - for f in *.xml; do SAX2Count -v=always -f -p $f; done
